# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow:

    def setupUi(self, MainWindow: QtWidgets.QMainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1990, 1104)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWidget{\n" "color : #000000;\n" "};\n" "\n" "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.total_exit = QtWidgets.QPushButton(self.centralwidget)
        self.total_exit.setGeometry(QtCore.QRect(650, 850, 611, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.total_exit.setFont(font)
        self.total_exit.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.total_exit.setStyleSheet(
            "QPushButton {\n"
            'font: 40pt "Segoe UI Variable Display Semib";\n'
            "color: #000000;\n"
            "border: 2px solid #000000;\n"
            "border-radius: 40px;\n"
            "border-style: outset;\n"
            "background: qradialgradient(\n"
            "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "radius: 1.35, stop: 0 #fff, stop: 1 #ffe724\n"
            ");\n"
            "padding: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "background:  qradialgradient(\n"
            "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "radius: 1.35, stop: 0 #fff, stop: 1 #f8ffae\n"
            ");\n"
            "}\n"
            ""
        )
        self.total_exit.setObjectName("total_exit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 110, 1071, 611))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("./img/Screenshot 2024-03-04 112257.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(8000, 8000))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, -30, 2021, 1211))
        self.label_2.setStyleSheet(
            "QLabel{\n" " background-color : #000000 ;\n" "}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.total_exit.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.total_exit.setText(_translate("MainWindow", "start"))